# This template is repurposed from the Create Mod bug report template at:
#   https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/.github/ISSUE_TEMPLATE/bug_report.yml
name: Bug Report
description: Create a bug report to help me improve Bygone Nether
labels: [ "bug" ]
body:
  -   type: textarea
      attributes:
        label: Describe the Bug
        description: A clear and concise description of what the bug is
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Reproduction Steps
        description: Tell me about the steps to reproduce the bug.
        value: |
          1.
          2.
          3.
          ...
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Expected Result
        description: A clear and concise description of what you expected to happen
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Screenshots and Videos
        description: If applicable, add screenshots or videos to help explain your problem.
      validations:
        required: false
  -   type: input
      attributes:
        label: Crash Report or Log
        description: Please add a **link** to the crash report or log that was created when this issue occured. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue. *My ability to bug fix is severely limited without a log of some kind.*
      validations:
        required: false
  -   type: input
      attributes:
        label: Operating System
        description: The operating system you were using when the bug occured
        placeholder: Windows 10
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Mod Version
        description: The version of the mod you were using when the bug occured
        options:
          - "1.3.2"
          - "1.3.1"
          - "1.3.0"
          - "1.2.1"
          - "1.2"
          - "1.1.2"
          - "1.1.1"
          - "1.1.0"
          - "1.0.3"
          - "1.0.2"
          - "1.0.1"
          - "1.0.0"
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the bug occured
        options:
          - "1.20.1"
          - "1.20"
          - "1.19.4"
          - "1.19.2"
          - "1.18.2"
          - "1.16.5"
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Mod Loader
        description: The mod loader you were using when the bug occured
        options:
          - "Forge"
          - "Fabric"
      validations:
        required: true
  -   type: input
      attributes:
        label: Mod Loader Version
        description: The version of the mod loader you were using when the bug occured
        placeholder: 36.2.0
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Other Mods
        description: Please list any other mods that were running when the crash happened.
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Additional Context
        description: Add any extra context about the bug here
      validations:
        required: false
  -   type: markdown
      attributes:
        value: "Thank you for taking the time to make this bug report and help improve Bygone Nether!"